name: edk2

on: push

jobs:
  windows:
    name: windows-build
    runs-on: windows-2019
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup build environment
        shell: cmd
        run: |-
          curl -SL --output ${{ github.workspace }}\nasm-2.16.01-win64.zip https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip
          powershell -Command "expand-archive -Path '${{ github.workspace }}\nasm-2.16.01-win64.zip' -DestinationPath 'c:\'"
          move c:\nasm-2.16.01 c:\nasm
          curl -SL --output ${{ github.workspace }}\iasl-win-20230331.zip https://acpica.org/sites/acpica/files/iasl-win-20230331.zip
          powershell -Command "expand-archive -Path '${{ github.workspace }}\iasl-win-20230331.zip' -DestinationPath 'c:\ASL'"
          curl -SL --output ${{ github.workspace }}\vs_buildtools.exe https://aka.ms/vs/16/release/vs_buildtools.exe
          ${{ github.workspace }}\vs_buildtools.exe --quiet --wait --norestart --add Microsoft.VisualStudio.Component.VC.CoreBuildTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.22000

      - name: Build BaseTools
        shell: cmd
        run: |-
          call ${{ github.workspace }}\vsenv.bat x86
          call ${{ github.workspace }}\edk2\edksetup.bat VS2019
          cd ${{ github.workspace }}\edk2\BaseTools
          nmake

      - name: Build
        shell: cmd
        run: |-
          call ${{ github.workspace }}\vsenv.bat x64
          call ${{ github.workspace }}\edk2\edksetup.bat VS2019
          set PACKAGES_PATH=${{ github.workspace }}/edk2;${{ github.workspace }}/edk2-libc;${{ github.workspace }}/edk2-test;${{ github.workspace }}/edk2-platforms/Silicon/Intel;${{ github.workspace }}/edk2-platforms
          cd ${{ github.workspace }}\edk2
          build -a IA32 -a X64 -t VS2019 -p OvmfPkg/OvmfPkgIa32X64.dsc -b RELEASE
