name: edk2

on: push

jobs:
  windows:
    name: windows-build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include: [
          { NAME: 'AppPkg',         PACKAGE: 'AppPkg',                             PACKAGE_DSC: 'AppPkg.dsc',         TARGET: 'RELEASE', ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
          { NAME: 'AppPkg',         PACKAGE: 'AppPkg',                             PACKAGE_DSC: 'AppPkg.dsc',         TARGET: 'DEBUG',   ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
          { NAME: 'ShellPkg',       PACKAGE: 'ShellPkg',                           PACKAGE_DSC: 'ShellPkg.dsc',       TARGET: 'RELEASE', ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
          { NAME: 'FatPkg',         PACKAGE: 'FatPkg',                             PACKAGE_DSC: 'FatPkg.dsc',         TARGET: 'RELEASE', ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
          { NAME: 'Ext4Pkg',        PACKAGE: 'Features/Ext4Pkg',                   PACKAGE_DSC: 'Ext4Pkg.dsc',        TARGET: 'RELEASE', ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
          { NAME: 'ASIXPkg',        PACKAGE: 'Drivers/ASIX',                       PACKAGE_DSC: 'Asix.dsc',           TARGET: 'RELEASE', ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
          { NAME: 'DisplayLinkPkg', PACKAGE: 'Drivers/DisplayLink/DisplayLinkPkg', PACKAGE_DSC: 'DisplayLinkPkg.dsc', TARGET: 'RELEASE', ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
          { NAME: 'OvmfPkg',        PACKAGE: 'OvmfPkg',                            PACKAGE_DSC: 'OvmfPkgX64.dsc',     TARGET: 'RELEASE', ARCH: 'X64',     TOOLCHAIN: 'VS2019',       ADDITIONAL_DEFINITION: '' },
        ]
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup build environment
        shell: cmd
        run: |-
          curl -SL --output ${{ github.workspace }}\nasm-2.16.01-win64.zip https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip
          powershell -Command "expand-archive -Path '${{ github.workspace }}\nasm-2.16.01-win64.zip' -DestinationPath 'c:\'"
          move c:\nasm-2.16.01 c:\nasm
          curl -SL --output ${{ github.workspace }}\iasl-win-20230331.zip https://acpica.org/sites/acpica/files/iasl-win-20230331.zip
          powershell -Command "expand-archive -Path '${{ github.workspace }}\iasl-win-20230331.zip' -DestinationPath 'c:\ASL'"
          curl -SL --output ${{ github.workspace }}\vs_buildtools.exe https://aka.ms/vs/16/release/vs_buildtools.exe
          ${{ github.workspace }}\vs_buildtools.exe --quiet --wait --norestart --add Microsoft.VisualStudio.Component.VC.CoreBuildTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.22000

      - name: Build BaseTools
        shell: cmd
        run: |-
          call ${{ github.workspace }}\vsenv.bat x86
          call ${{ github.workspace }}\edk2\edksetup.bat ${{ matrix.TOOLCHAIN }}
          cd ${{ github.workspace }}\edk2\BaseTools
          nmake

      - name: Build
        shell: cmd
        run: |-
          call ${{ github.workspace }}\vsenv.bat x64
          call ${{ github.workspace }}\edk2\edksetup.bat ${{ matrix.TOOLCHAIN }}
          set PACKAGES_PATH=${{ github.workspace }}/edk2;${{ github.workspace }}/edk2-libc;${{ github.workspace }}/edk2-test;${{ github.workspace }}/edk2-platforms/Silicon/Intel;${{ github.workspace }}/edk2-platforms
          cd ${{ github.workspace }}\edk2
          build -a ${{ matrix.ARCH }} -t ${{ matrix.TOOLCHAIN }} -p ${{ matrix.PACKAGE }}/${{ matrix.PACKAGE_DSC }} -b ${{ matrix.TARGET }} ${{ matrix.ADDITIONAL_DEFINITION }}

      - uses: actions/upload-artifact@v3
        with:
          name: edk2_${{ matrix.NAME }}_${{ matrix.TARGET }}_${{ matrix.TOOLCHAIN }}_${{ matrix.ARCH }}_${{ github.sha }}
          path: |-
            Build/**/*.efi
            Build/**/FV/*.fd
            Build/BUILDLOG*.*
            Build/CI_*.*
            Build/SETUPLOG.*
            Build/UPDATE*.*
            Build/**/AutoGen.*
            edk2-libc/AppPkg/Applications/Python/Python-3.6.8/Lib/
            edk2-libc/StdLib/Efi/StdLib/etc/